version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  hdfsmirror.main:
    level: INFO
    handlers: [console]
    propagate: no
  hdfsmirror.thread:
    level: INFO
    handlers: [console]
    propagate: no
  hdfsmirror.WebHDFS:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: WARN
  handlers: [console]
